version: 2
jobs:
  build:
    docker:
      - image: qawolf/playwright-ci:v0.6.0
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          command: |
            # Start local server
            npm run start & 
            npx wait-on http://localhost:3000
            npx qawolf test --headless --all-browsers
          environment:
            # configure tests with environment variables
            QAW_ARTIFACT_PATH: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
# # example for running on a schedule, edit to suit your use case
# # documentation: https://circleci.com/docs/2.0/configuration-reference/#schedule
# workflows:
#   version: 2
#   on_schedule:
#     jobs:
#       - build
#     triggers:
#       - schedule:
#           # test on schedule using cron syntax
#           cron: "0 * * * *" # every hour
#           filters:
#             branches:
#               only:
#                 - master
